Add ability to ignore certain users comments
ralphbean/bugwarrior pull request #1039
Opened 2024-03-18 21:19 UTC by thekad

Some build/CI systems can become too noisy, you still want to pull real people's comments and ignore bot accounts when adding annotations.

2024-03-19 21:05 UTC, ryneeverett requested changes
Implementation looks fine but these options need to be documented and tested.

2024-03-19 21:05 UTC, ryneeverett commented on bugwarrior/services/gerrit.py
>              # Gerrit messages are really messy
This comment was about the cleaning of the message below. You should move it below your addition or, perhaps better, delete it.

2024-03-19 22:06 UTC, thekad commented
> Implementation looks fine but these options need to be documented and tested.

I'll add the test bits for github, there is no annotation testing done at all for gerrit but I can take a shot at it.

Question: Do you think it makes sense to leave these options on a per-service basis?

2024-03-19 23:58 UTC, ryneeverett commented
> I'll add the test bits for github, there is no annotation testing done at all for gerrit but I can take a shot at it.

if you can't test gerrit that's ok. Github is the critical one due to it's popularity and number of features.

> Question: Do you think it makes sense to leave these options on a per-service basis?

Yes, I think we should leave them on a per-service basis. Unfortunately, it isn't a safe assumption that usernames are owned by the same entity (or in the case of bots, running the same software) across services and I don't think we should introduce that assumption here. For example, you might want to ignore a spammer who is username-squatting on one platform without ignoring the legitimate user on another platform.

2025-05-01 21:14 UTC, ryneeverett requested changes
Just about there, thanks! Still need:

- [x] Gerrit documentation
- [x] Please address or respond to [this review comment](https://github.com/GothenburgBitFactory/bugwarrior/pull/1039/files#r1531088975).

2025-05-01 22:11 UTC, thekad commented
I amended the gerrit docs with a similar "sync content" section as github, and removed the comment

2025-05-02 00:47 UTC, ryneeverett approved these changes

2025-05-02 16:02 UTC, merged