Handle redmine not returning estimated hours.
ralphbean/bugwarrior pull request #967
Opened 2023-01-30 13:50 UTC by fedegiova

In our setup the estimated_hours and spent_hours fields might be empty, this trigger an exception in taskwarrior that it cannot convert 0.0 to a duration.

ERROR:bugwarrior.db:Unable to add task: b"The duration value '0.0' is not supported." Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/bugwarrior/db.py", line 439, in synchronize
    new_task = tw.task_add(**issue)
  File "/usr/lib/python3.10/site-packages/taskw/warrior.py", line 704, in task_add
    stdout, stderr = self._execute('add', *args)
  File "/usr/lib/python3.10/site-packages/taskw/warrior.py", line 498, in _execute

The command line for taskwarrior invocation is:

[b'task'
...
b'rc.uda.redminespenthours.type=duration', b'rc.uda.redminespenthours.label="Redmine Spent Hours"', b'rc.uda.redmineestimatedhours.type=duration', ...
b'redminespenthours:"0.0"'
]

The patch makes sure that the value is formatted correctly for the duration type

2023-01-31 00:16 UTC, ryneeverett requested changes
To clarify my understanding of the bug: because `0.0` is falsey, it was getting passed through as a `float` rather than getting properly formatted.

The tests fail because this patch changes the behavior to return a formatted `0` rather than `None` when these values are falsey. This would change the end behavior by inserting the formatted `0` value into every redmine task rather than omitting it when the server doesn't return it. I think a better solution (which would also fix the tests) would be to explicitly handle this condition, i.e.:

```py
if spent_hours or spent_hours == 0.0:
```

This has the same result as your patch in the `0.0` case because `self.get_converted_hours('0.0 hours')` will call `task calc 0.0 hours` which returns `PT0S`.

2023-02-08 07:19 UTC, fedegiova commented
You're right, I'll test your fix in  a couple of days and I'll upload a new patch if it works.

Thanks
Federico

2023-02-13 11:28 UTC, fedegiova commented
Hi! I've tested your solution and it's working fine, it fix the previous problem and also correctly update the task database.

I've reverted mine and applied your modifications.

Regards
Federico

2023-02-13 19:35 UTC, ryneeverett approved these changes

2023-02-17 02:22 UTC, merged